### PR TITLE
add Cython and Java version

### PR DESCRIPTION
**Pull request by zocker-160**
as requested :)

### CODE REVIEW

**Comment by Matt-London** [comment]
@zocker-160 Ahh very nice thank you! I'll take a look later tonight or tomorrow but merge it now.

**Comment by Matt-London** [comment]
@zocker-160 Cython version looks very cool! I haven't had the opportunity to play around with Cython yet, but I'll definitely look into it in more detail when I have more time. Thank you for your contributions!

**Comment by zocker-160** [comment]
@Matt-London sure no problem 👍 
Cython is great actually, you get C performance with a syntax more similar to Python and you can flawlessly integrate it into existing python code

**Comment by Matt-London** [comment]
@zocker-160 Yeah, I'll definitely take a look!

**Pull request merged**
